language: ruby
rvm:
  - "2.1.3"
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
#  - gem install rspec
  - bundle exec rspec test/
before_script:
  - mysql -e 'create database books_test'
bundler_args: --binstubs=./bundler_stubs
